configversion: 1
# Do not change this value

server:
  host: 0.0.0.0
  motd: "Skycloud Server"
  port: 3127
  maxconnections: 10

database:
  file: "./skycloud.db"

logging:
  level: "INFO"
  file: "./skycloud.log"
